Repository ytti/oxidized, pull requests merged in 2019-03, with the labels that each got.

#1630 Added ruby 2.3 install on centos 7
  README.md
Labels: user_pending

#1722 change from :paranoid to :verify_host_key for net-ssh 5
  .rubocop_todo.yml
  CHANGELOG.md
  lib/oxidized/input/ssh.rb
  spec/input/ssh_spec.rb
Labels: bug

#1743 Fixed dependencies for net-ssh (#1742)
  CHANGELOG.md
  oxidized.gemspec
Labels: regression

#1762 Remove NetgearXS716, use Netgear instead.
  docs/Model-Notes/Netgear.md
  docs/Supported-OS-Types.md
  lib/oxidized/model/netgear.rb
  lib/oxidized/model/netgearxs716.rb
Labels: device_model, user_pending

#1759 Documentation to add feature to list unsaved changes to a Cisco switch
  docs/Model-Notes/README.md
  docs/Model-Notes/ios.md
Labels: documentation, user_pending
