Repository ytti/oxidized, pull requests merged in 2019-04, with the labels that each got.

#1767 Docs: SSH public-key authentication
  docs/Configuration.md
Labels: documentation

#1764 Explicit stringio to string type conversion in nagios check
  CHANGELOG.md
  extra/nagios_check_failing_nodes.rb
Labels: bug, user_pending

#1783 Add support for Icotera
  CHANGELOG.md
  docs/Supported-OS-Types.md
  lib/oxidized/model/icotera.rb
Labels: device_model, user_pending
